[14.0] [IMP] fieldservice_equipment_website
OCA/field-service pull request #1016
Opened 2022-12-09 18:55 UTC by marcos-mendez

This adds also the equipment to the website and fixes my previous blinded PR

2022-12-09 19:13 UTC, max3903 requested changes

2022-12-09 19:13 UTC, max3903 commented on .github/workflows/pre-commit.yml
> +      - "14.0-fsm*"
```suggestion
```

2022-12-09 19:13 UTC, max3903 commented on fieldservice_equipment_stock/views/fsm_equipment.xml
> +                    />
This is already in #1013

2022-12-09 19:13 UTC, max3903 commented on fieldservice_equipment_website/__manifest__.py
> +        "base",
```suggestion
```

2022-12-09 19:13 UTC, max3903 commented on fieldservice_equipment_website/__manifest__.py
> +        "website",
```suggestion
        "website",
        "fieldservice",
```

2022-12-09 19:13 UTC, max3903 commented on fieldservice_equipment_website/views/fieldservice_equipment_website_templates.xml
> +                                    <p>RESGISTRO ANVISA: <t
Should be in english

2022-12-12 12:33 UTC, marcos-mendez commented on fieldservice_equipment_stock/views/fsm_equipment.xml
> +                    />
How can i remove this only from this PR?

2022-12-12 12:35 UTC, marcos-mendez commented on fieldservice_equipment_website/views/fieldservice_equipment_website_templates.xml
> +                                    <p>RESGISTRO ANVISA: <t
Ok gonna make a new branch and close this PR is alot of stuff to fix.

2022-12-14 00:55 UTC, marcos-mendez commented
I'll open later when understand better how this works. Still don't figure it out.

2022-12-14 00:55 UTC, closed without merging