A lot of stuff
OCA/field-service pull request #1022
Opened 2022-12-22 22:33 UTC by marcos-mendez

Fixing also this #1011 and  other stuff with pre-commit

2022-12-22 22:39 UTC, marcos-mendez commented
@marcelsavegnago and @rvalyi if you could help me review this i'll appretiate

2022-12-22 22:48 UTC, rvalyi requested changes
It seems you are changing/adding several modules. I would say start with basic things and submit more modules for review as you have some PRs getting merged... 
In general, It's unlikely people spend time reviewing hundreds of lines of third party code from several modules if you don't convince them first it's worth their time with smaller steps...

2022-12-22 22:48 UTC, rvalyi commented on fieldservice_equipment_qrcode/reports/fieldservice_equipment_report_template.xml
> +                                t-esc="o.current_location_id.name"
Reports should be in English and translated only using the i18n files.

2022-12-22 22:54 UTC, marcos-mendez commented
I dont know how to push only one module
can you teach me ?

2022-12-22 22:54 UTC, marcos-mendez commented
@rvalyi

2022-12-22 22:55 UTC, closed without merging

2022-12-23 04:47 UTC, marcelsavegnago commented
> @marcelsavegnago and @rvalyi if you could help me review this i'll appretiate

@marcos-mendez Unfortunately, as it stands, I can't help with the review. I suggest you do the PRs by module or feature/improvement. Also, from what I've seen, the commits need a review/cleanup.

I suggest you make the PRs similar to what your developer did for your fork. If in doubt, check the repository's PR history and base it on the way other collaborators do.

2022-12-23 04:51 UTC, marcelsavegnago commented
Example of a commit that is not good. I recommend making commits separated by module as this makes porting commits forward or backwards easier.

https://github.com/OCA/field-service/pull/1022/commits/89e896dac8eb7925d0496c29342b8278d810141a