[14.0][FIX] fieldservice: fix intermittent test failures
OCA/field-service pull request #1040
Opened 2023-01-20 15:01 UTC by PicchiSeba

Some times when submitting a PR automatic tests fail. I suspect it is caused by the evaluation of datetime.now() not being done immediately (it could be a machine with not enough resourses available).

I am aware that this is more a 'hack' than i fix, but for the moment I am not aware of more elegant solutions.

2023-01-20 18:12 UTC, max3903 approved these changes

2023-01-27 10:10 UTC, hparfr requested changes
Freezegun maybe ? 
https://github.com/odoo/odoo/blob/14.0/addons/project/tests/test_project_recurrence.py#L10

2023-01-27 11:47 UTC, PicchiSeba commented
I applied the suggestion

2023-01-27 13:40 UTC, hparfr commented on fieldservice/tests/test_fsm_order.py
> +            # timedelta is necessary when the evaluation is not immediate
wrong comment

2023-01-27 15:23 UTC, PicchiSeba commented on fieldservice/tests/test_fsm_order.py
> +            # timedelta is necessary when the evaluation is not immediate
Nice catch, I removed it now

2023-01-30 11:04 UTC, hparfr approved these changes

2023-01-30 11:04 UTC, hparfr commented
/ocabot merge minor

2023-02-01 09:42 UTC, PicchiSeba commented
Is there anything that I can do to fix the [pre-commit error](https://github.com/OCA/field-service/actions/runs/4043176312/jobs/6951788951) preventing this PR merge?

2023-02-01 15:18 UTC, max3903 commented
@PicchiSeba You can try downgrading node in the pre-commit config to see it fixes the issue or look at other repos in the OCA to check if they got the issue and how they fixed it.

2023-02-14 14:26 UTC, PicchiSeba commented
included in #1039

2023-02-14 15:45 UTC, PicchiSeba commented
closing because it has been fixed already

2023-02-14 15:45 UTC, closed without merging