[14.0] [ADD] fieldservice_order_portal
OCA/field-service pull request #1146
Opened 2023-12-11 11:47 UTC by renda-dev

Bridge module between `fieldservice` and `portal` that allows portal users to monitor work orders related to their locations.

2024-01-03 14:28 UTC, aleuffre approved these changes
Code review, LGTM.

Suggest maybe renaming simply to `fieldservice_portal`?

2024-01-09 14:24 UTC, renda-dev commented
> Code review, LGTM.
> 
> Suggest maybe renaming simply to `fieldservice_portal`?

Done, thanks for the suggestion! @aleuffre

2024-01-10 01:24 UTC, marcelsavegnago requested changes

2024-01-10 01:24 UTC, marcelsavegnago commented on fieldservice_portal/controllers/fsm_order_portal.py
> +        ["/my/workorder/<int:order_id>"],
It's not better if it's fsm_order instead worker orders?

2024-09-22 12:17 UTC, closed without merging