[18.0][MIG]fieldservice_account_analytic
OCA/field-service pull request #1226
Opened 2024-10-15 21:55 UTC by EdgarRetes

@max3903

2024-10-16 05:07 UTC, max3903 commented
/ocabot migration fieldservice_account_analytic

2024-11-15 21:11 UTC, max3903 commented
/ocabot migration fieldservice_account_analytic

2024-11-22 22:14 UTC, EdgarRetes commented
@brian10048 @max3903

2024-11-23 20:17 UTC, max3903 commented on fieldservice_account_analytic/readme/USAGE.md
> +
```suggestion
* Go to Field Service > Master Data > Location
* Create or select a location
* Go to the Accounting tab
* Select a new or existing analytic account
```

2024-11-23 20:23 UTC, max3903 commented
@EdgarRetes We need to create 3 analytic plans:
* FSM Orders
* FSM Locations
* FSM Routes

We also need to activate the following settings/groups:
- Technical/Analytic Accounting
- Technical/Show Full Accounting Features --> Add a dependency on account_usability

2024-11-27 20:21 UTC, max3903 commented on fieldservice_account_analytic/data/analytic_plan.xml
> +        <field name="name">FSM Orders</field>
FSM Locations

2024-11-27 20:21 UTC, max3903 commented on fieldservice_account_analytic/data/analytic_plan.xml
> +        <field name="name">FSM Orders</field>
```suggestion
        <field name="name">FSM Routes</field>
```

2024-11-27 20:22 UTC, max3903 commented on fieldservice_account_analytic/data/analytic_plan.xml
> +        <field name="name">FSM Orders</field>
```suggestion
        <field name="name">FSM Locations</field>
```

2024-11-29 22:41 UTC, EdgarRetes commented
> @EdgarRetes We need to create 3 analytic plans:
> 
>     * FSM Orders
> 
>     * FSM Locations
> 
>     * FSM Routes
> 
> 
> and:
> 
>     * Create a new account in the FSM Orders plan for each order
> 
>     * Create a new account in the FSM Locations plan for each location
> 
>     * CReate a new account in the FSM Routes plan for each route
> 
> 
> When creating the customer invoice, vendor bill line or timesheet entry, we need to set the corresponding analytic account in each plan.
> 
> We also need to activate the following settings/groups:
> 
>     * Technical/Analytic Accounting
> 
>     * Technical/Show Full Accounting Features --> Add a dependency on account_usability

Account usability hasn't been merged yet. Once it is done you can test it

https://github.com/OCA/account-financial-tools/pull/1981

2024-11-30 17:58 UTC, max3903 commented on fieldservice_account_analytic/views/fsm_route.xml
> +            </xpath>
```suggestion
            <field name="day_ids" position="after">
                <field name="analytic_account_id" />
            </field>
```

2024-11-30 18:06 UTC, max3903 commented on fieldservice_account_analytic/models/fsm_order.py
> +            }
```suggestion
```

2024-11-30 18:06 UTC, max3903 commented on fieldservice_account_analytic/models/fsm_route.py
> +            }
```suggestion
```

2024-12-06 13:58 UTC, max3903 commented
@EdgarRetes 

I think all the features around route can be moved to `fieldservice` and hidden with a group (activated in the setting).

All the analytic features can be moved to `fieldservice_account` and hidden with the existing group/setting.

2024-12-06 18:42 UTC, EdgarRetes commented
> @EdgarRetes
> 
> I think all the features around route can be moved to `fieldservice` and hidden with a group (activated in the settings).
> 
> All the analytic features can be moved to `fieldservice_account` and hidden with the existing group/setting.

Do you have any example of a repository that does this?

2025-03-10 16:13 UTC, are-agilebg commented
@max3903 since the changes you're proposing are, if I'm not mistaken, refactoring of the actual logic and this PR is stale for a long time, don't you think we can postpone the refactoring to a later PR and prioritize the pure migration of the logic as-is? Also, this module not migrated 'blocks' the migration of fieldservice_isp_account.

Do you think this could be feasible? Thanks

2025-03-10 19:42 UTC, max3903 commented
Let me discuss it with @santiagordz and give it higher priority.

2025-04-28 09:52 UTC, are-agilebg commented
> Let me discuss it with @santiagordz and give it higher priority.

Sorry if I bother you: have you had a chance to discuss it?

2025-04-28 17:31 UTC, max3903 commented
> Sorry if I bother you: have you had a chance to discuss it?

Nope. @SMaciasOSI Can you get this in the todo list of @dcamacho20

2025-05-22 11:21 UTC, are-agilebg commented
> > Sorry if I bother you: have you had a chance to discuss it?
> 
> Nope. @SMaciasOSI Can you get this in the todo list of @dcamacho20?

Thanks for looking into it! We'll probably start anyway to migrate fieldservice_isp_account internally to 18.0 using this open PR as a dependency.

2025-08-19 11:34 UTC, vvrossem commented
Hello :wave: 
I'm migrating `fieldservice_isp_account` (https://github.com/OCA/field-service/pull/1442) but several unit tests are failing because of required fields introduced in `fieldservice_account_analytic`.
Example: `fieldservice_crm` (which doesn't depend on `fieldservice_account_analytic`) fails to create a `fsm.location` because the required field `customer_id` is not present.

@EdgarRetes would you mind rebasing this PR? I suspect the CI will fail too: some modules have been merged meanwhile.

2025-08-19 17:20 UTC, ivantodorovich requested changes
Hello 👋🏻 !

I just did a review commit by commit.
Some of my comments may be outdated, as the code is overwritten by following commits. However, the content is still valid in most cases.

Can you clean up a bit the commits, please?
I believe the changes are not atomic and well organized. If not possible, then it's better to squash everything into the migration commit and write a nice message describing the main changes.

Some things are blocking for me, like the addition of the new dependency, and the new init_hook.

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/analytic_account.py
> +                        _("No analytic account set " "on the order's Location.")
Please use `self.env._`

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/analytic_account.py
> +        for vals in vals_list:
I know it was like this before, but please lets only loop if `vals.get("fsm_order_id")`, as it makes no sense to get into this iteration otherwise

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/analytic_account.py
> +    _inherit = "account.analytic.account"
Can we split this into two files: `account_analytic_line.py`  and `account_analytic_account.py` ?

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/analytic_account.py
> +    # route_id = fields.One2many("tms.route", "analytic_account_id", copy=False)
What's with this commented out line?

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/fsm_order.py
> +            }
Please move the vals preparation to a separate method. This makes it possible to easily override in other modules if needed. e.g: `_prepare_analytic_account_vals`

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/fsm_order.py
> +        analytic_account = self.env["account.analytic.account"].create(
I think we should only create it if it's not already set in `vals`.

```py
records = super().create(vals_list)
if not vals.get("analytic_account_id"):
    for record in records:
        analytic_account_vals = record._prepare_analytic_account_vals()
        analytic_account = self.env["account.analytic.account"].create(vals)
        record.analytic_account_id = analytic_account
```

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/fsm_order.py
> +    @api.model
use `@api.model_create_multi`

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/fsm_order.py
> +                "fsm_order_id": record,
set also the `company_id` and `partner_id`

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/fsm_location.py
> +        analytic_account = self.env["account.analytic.account"].create(
Same comments than the `fsm.order` model:
- use model_create_multi
- separate method for vals preparation
- create only if not explicitly set in vals

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/models/fsm_location.py
> +from odoo import _, api, fields, models
Use self.env._ instead, everywhere

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/__manifest__.py
> +        "account_usability",
What's with this new dependency?

2025-08-19 17:20 UTC, ivantodorovich commented on fieldservice_account_analytic/init_hook.py
> +            user.write({"groups_id": [(4, group_analytic_accounting.id)]})
This is not correct.

You can't just give this group to every user in the db

2025-08-19 17:22 UTC, ivantodorovich commented on fieldservice_account_analytic/models/analytic_account.py
> +    # route_id = fields.One2many("tms.route", "analytic_account_id", copy=False)
NOTE: This line is overwriten in a following commit.
Still: clearly commits are not atomic and require some cleaning

2025-08-21 17:49 UTC, ivantodorovich commented on fieldservice_account_analytic/data/ir_rule.xml
> +        <field name="domain_force">[(1, '=', 1)]</field>
This is coming from previous versions, but it's not correct.
It grants too much power.

It should only grant access to lines having a `fsm_order_id`, IMO:

```suggestion
        <field name="domain_force">[('fsm_order_id', '!=', False)]</field>
```

2025-08-21 17:49 UTC, ivantodorovich commented on fieldservice_account_analytic/data/ir_rule.xml
> +        <field name="perm_unlink" eval="True" />
Same comment as before, but it's also giving too much power.
The dispatcher should probably only see them, but I'm not sure if it should modify them 🤔 
TBD

```suggestion
        <field name="domain_force">[('fsm_order_id', '!=', False)]</field>
        <field name="groups" eval="[(4, ref('fieldservice.group_fsm_dispatcher'))]" />
        <field name="perm_read" eval="True" />
        <field name="perm_write" eval="False" />
        <field name="perm_create" eval="False" />
        <field name="perm_unlink" eval="False" />
```

2025-08-21 17:49 UTC, ivantodorovich commented on fieldservice_account_analytic/data/ir_rule.xml
> +</odoo>
Moreover, the user should be able to see and record his own timesheets

```suggestion
    <record id="analytic_account_fsm_user" model="ir.rule">
        <field name="name">account.analytic.line.fsm.user</field>
        <field name="model_id" ref="model_account_analytic_line" />
        <field name="domain_force">[('fsm_order_id', '!=', False), ('user_id', '=', user.id)]</field>
        <field name="groups" eval="[Command.link(ref('fieldservice.group_fsm_user'))]" />
    </record>
</odoo>
```

2025-08-21 17:49 UTC, ivantodorovich commented on fieldservice_account_analytic/data/ir_rule.xml
This file should be moved to `security/`

2025-08-21 17:49 UTC, ivantodorovich commented on fieldservice_account_analytic/models/account_move.py
> +        return super().create(vals_list)
This should be done in an override of `_compute_analytic_distribution`, instead of a `create` override.

2025-08-21 17:49 UTC, ivantodorovich commented on fieldservice_account_analytic/models/analytic_account.py
> +        self.name = self.product_id.name if self.product_id else False
This is too invasive for other modules adding their own analytic lines.

I'm not sure we want this, anyway.

My recommendation would be to remove it.
And if we really want it, it shuold be limited only on those analytic.lines that have a `fsm_order_id`

```suggestion
```

2025-08-21 17:49 UTC, ivantodorovich commented on fieldservice_account_analytic/models/fsm_location.py
> +        if self.env.user.has_group("analytic.group_analytic_accounting"):
It shouldn't matter if the user creating the FSM order has access to accounting or not.
The behavior should be the same.

Moreover, the account should be created only if it's not already provided in the vals. Otherwise we'd be overwriting it.

2025-08-21 17:49 UTC, ivantodorovich commented on fieldservice_account_analytic/models/fsm_location.py
> +                record.analytic_account_id = analytic_account
This for..loop is totally wrong.

It's looping through all the `vals` in `vals_list`, but for each iteration it's assigning the created analytic account to `record` (which in fact should be spelled `records` [plural]).

So, all the created records will end up with the same analytic account --> the one created for the last of them

2026-01-25 12:26 UTC, closed without merging