[IMP] fieldservice: Allow users to submit stock requests
OCA/field-service pull request #226
Opened 2019-05-30 04:22 UTC by max3903

2019-05-30 06:20 UTC, osi-scampbell approved these changes

2019-05-30 18:29 UTC, patrickrwilson approved these changes

2019-05-31 06:11 UTC, bodedra approved these changes
LGTM :+1:

2019-06-04 14:49 UTC, smangukiya approved these changes

2019-06-04 16:12 UTC, HviorForgeFlow requested changes
Travis is red

2019-06-10 16:47 UTC, max3903 commented
@aheficent I know. This is pending a decision here:
https://github.com/OCA/stock-logistics-warehouse/pull/605#issuecomment-500489478

2019-07-05 15:43 UTC, closed without merging