field service team
OCA/field-service pull request #26
Opened 2018-10-16 13:29 UTC by robertrottermann

Field Service Teams
===================
Teams for managing the field service jobs.

Specifications
==============
- A team is a group of field workers
-  it can have:
    - A team leader, and a number of team members.
    - Some basic skills a each team member needs 
    - A minimum size
    - A maximum size
- Jobs will be assigned to teams.
- When we select a team for a job, the available employees will be listed
  and can be select from that list to create a crew.
- Once an field worker is engaged in a job (crew ?), he cannot be engaged in another job(ongoing)
  at the same time.
- When he is finished with the current job, he will be available for next job.

2018-10-16 14:27 UTC, aitorbouzas commented
Hi Robert, I just saw your question in the mailing list.
1. You can edit the name of your PR right here. Click in the three dots at the top right corner of the first commentary in this PR and then click Edit.
2. To check the runbot error/warning go to the runbot page into your build, then click the gear and read the different logs (note that a warning in the logs also marks the check as failed)
Logs now show:
```
2018-10-16 13:34:18,128 165 WARNING openerp_test odoo.models: ir.actions.server.create() includes unknown fields: condition

2018-10-16 13:34:18,170 165 WARNING openerp_test odoo.models: ir.ui.menu.write() with unknown fields: load_xmlid

2018-10-16 13:34:18,713 165 WARNING openerp_test odoo.modules.loading: The model fsm.skills has no access rules, consider adding one. E.g. access_fsm_skills,access_fsm_skills,model_fsm_skills,base.group_user,1,0,0,0
```
3. To make different commits and then squash them make sure you use this git commands:

For commits:
```
git commit --all --fixup HEAD
```

For squashing all your commits automatically:
```
git rebase -i origin/12.0 --autosquash
```

2018-10-16 14:45 UTC, robertrottermann commented
thanks a lot,
editing of the commit message works fine, but I can not change the title of the PR.
Or can I?
robert

2018-10-16 14:52 UTC, aitorbouzas commented
Oh, sure! I told you about the wrong button to edit. There's a button "Edit" at the right of the PR title :)

2018-10-16 22:38 UTC, dreispt commented
How do these Teams relate to "Stage Workflows?
Is it expected that different Teams follow different workflow steps?
Can the same Team use different Workflows in two different Jobs?

2018-10-16 22:41 UTC, dreispt commented on fsm_team_handler/models/fsm_person_extended.py
> +    def write(self, vals):
I think we don't need this method at all.

2018-10-16 22:46 UTC, dreispt reviewed
I would say this intends to implement #5 and #9.

2018-10-16 22:46 UTC, dreispt commented on fsm_team_handler/models/res_config_settings_teams.py
> +        string='Manage RedFSM Teams',
Red?

2018-10-16 22:46 UTC, dreispt commented on fsm_team_handler/models/team_handler.py
> +            string="Team Availability"
Deserves a `help` tooltip explaining the concept.
Why not a Many2one?

2018-10-17 07:20 UTC, lintocybrosys commented on fsm_team_handler/models/fsm_person_extended.py
> +    def write(self, vals):
What about the case where we need to create a 'person' for an existing 'customer'. Currently, when we create a 'person', a 'customer' will be created and linked with that  'person'. I think the above method will be useful in the reverse process, i.e, creating a 'person' for an existing 'customer'.

2018-10-17 07:55 UTC, dreispt commented on fsm_team_handler/models/fsm_person_extended.py
> +    def write(self, vals):
That's already described in the specs and implemented: 
there is a Wizard to convert a Parnter into a Person: https://github.com/OCA/field-service/blob/11.0/fieldservice/wizard/fsm_wizard.py

2018-10-19 17:01 UTC, moylop260 requested changes

2018-10-19 17:01 UTC, moylop260 commented on fsm_team_handler/__init__.py
> +# -*- coding: utf-8 -*-
For python3.5 is not needed use coding magic comment.
Remove this line for all python files.

2018-10-19 17:01 UTC, moylop260 commented on fsm_team_handler/__manifest__.py
> +    'description': """Jobs can be assigned to a team.
The README.rst file is used instead of this description, then you should delete this description from manifest.

2018-10-19 17:01 UTC, moylop260 commented on fsm_team_handler/__manifest__.py
> +    'author': "redO2oo.ch2",
Add to `redO2oo.ch2,Odoo Community Association (OCA)`

2018-10-19 17:01 UTC, moylop260 commented on fsm_team_handler/__manifest__.py
> +    'name': "Field Service Teams",
`license` is missing

2018-10-19 17:01 UTC, moylop260 commented on fsm_team_handler/models/fsm_person_extended.py
> +            string="Availability",
Use just 4 spaces here instead of 8

2018-10-19 17:01 UTC, moylop260 commented on fsm_team_handler/models/team_handler.py
> +                teams = user.fsm_team_ids and\
You can use
```python
teams = (user.fsm_team_ids and
         user.fsm_team_ids.ids or [])  # same spaces previous line
```
or


```python
teams = user.fsm_team_ids and \
    user.fsm_team_ids.ids or []   # 4 spaces
```

2018-10-21 16:43 UTC, dreispt commented
I see a support ticket module being bundled here.
It should be proposed in a separate PR, to have a smaller changesets (PR with big changesets are difficult to review, and so have a hard time to get reviewed; the best approach is an iterative one, "feeding" features for review one at a time).

Also, I would like to discuss the design decisions regarding support tickets, but that's off topic here.

2019-01-23 18:54 UTC, closed without merging