[Add] New Module: fieldservice_crm
OCA/field-service pull request #357
Opened 2019-10-01 20:43 UTC by patrickrwilson

This adds a new module called fieldservice_crm which connects field service orders with the sales crm module. This is useful for when personnel are needed to travel to the location for evaluation or surveys before a quote gets generated.

2019-10-01 20:45 UTC, patrickrwilson commented
ping @max3903 and @osi-scampbell

2019-10-02 23:59 UTC, brian10048 requested changes
Great addition!

Can you add an option to enable this module in the base field service settings?

2019-10-03 04:31 UTC, patrickrwilson commented
> Great addition!
> 
> Can you add an option to enable this module in the base field service settings?

Yes, I won't be able to get to this until maybe later next week but will definitely add that.

2019-10-10 15:28 UTC, patrickrwilson commented
@brian10048 updated the settings to include this module so I think it's ready for more review. 
Ping @max3903 @osi-scampbell

2019-10-10 15:53 UTC, max3903 commented on fieldservice_crm/views/fsm_location.xml
> +                    <field string="Opportunites" name="opportunity_count" widget="statinfo"/>
```suggestion
                    <field string="Opportunities" name="opportunity_count" widget="statinfo"/>
```

2019-10-10 15:54 UTC, max3903 approved these changes

2019-10-10 16:36 UTC, brian10048 approved these changes

2019-10-10 16:44 UTC, merged