[FIX] fieldservice_purchase: Access rights
OCA/field-service pull request #545
Opened 2020-04-03 23:39 UTC by max3903

2020-04-04 05:59 UTC, bodedra approved these changes
LGTM :+1:

2020-04-04 07:28 UTC, nelsonramirezs approved these changes
LGTM

2020-04-04 09:18 UTC, dreispt approved these changes

2020-04-04 09:24 UTC, dreispt requested changes

2020-04-04 09:24 UTC, dreispt commented on fieldservice_purchase/security/ir.model.access.csv
> +access_purchase_order_fsm_user,purchase.order.fsm.user,model_purchase_order,fieldservice.group_fsm_user,1,0,0,0
```suggestion
access_purchase_order_fsm_user,purchase.order.fsm.user,purchase.model_purchase_order,fieldservice.group_fsm_user,1,0,0,0
```

2020-04-08 23:06 UTC, max3903 commented
/ocabot merge minor

2020-04-08 23:18 UTC, merged