[FIX] fieldservice: fix timezone issue with Order filters
OCA/field-service pull request #609
Opened 2020-07-23 23:37 UTC by dreispt

context_today does not work correctly for datetime filters,
it is being used durectly to compare wuth UTC stored datetimes.
To get the expected results, datetime.utcmow() must be used instead.

2020-07-23 23:40 UTC, smangukiya approved these changes

2020-07-23 23:42 UTC, smangukiya commented
@dreispt : We need more approval to get this merge.  I can not set more reviewers to this so please do that from your end. Thanks

2020-07-23 23:45 UTC, brian10048 commented
I will be glad to test and provide a review soon

2020-07-24 01:37 UTC, brian10048 commented
I don't think this solves the issue.

I am testing on the runbot build.
I created an order for todays date at 00:00:01
I applied the Today filter
No orders show in the view.

I then made several attempts to the order schedule start time.  For me, the cutoff seems to be at 20:00:00.  An order with time of 19:59:59 (with today's date) will not show in today's order filter.  However, 20:00:00 and past show in the Today filter.  Similarly, I put another order for tomorrow's date. Anytime before 20:00:00 tomorrow will show up in the Today's filter, even though it is on tomorrow's date.

I tried changing the User Preferences time zone.  Changes to the time zone had no effect on the result.  My computer is set to timezone of US/Eastern which is 4 hours from UTC and equivalent to the difference (00:00:00 to 20:00:00)

2020-07-24 01:53 UTC, brian10048 commented
Testing on my current database to reproduce the bug (without this PR):

An order set for yesterday's date at 20:00:00 will show in 'Today's' filter option.  An order will not show in the Today filter if it's scheduled start date is after today's date at 19:59:59

Once again, the offset for me locally is 4 hours from UTC

2020-07-24 02:20 UTC, brian10048 requested changes
https://github.com/odoo/odoo/blob/f7567f10dd0cc936336066e7835c908fde163dc0/addons/stock_landed_costs/views/stock_landed_cost_views.xml#L193:199

Similar concept from Odoo code uses context_today, but without times

2020-08-13 19:40 UTC, osi-scampbell commented
@brian10048 @dreispt @max3903 Hey Team, I was able to reproduce this issue using runbot here:
![image](https://user-images.githubusercontent.com/39602586/90179184-edd5cf00-dd61-11ea-81cf-bbf253bf57bc.png)
Observe when the filter is applied we cannot see our FSM Order for today (08/13)
![image](https://user-images.githubusercontent.com/39602586/90179247-0219cc00-dd62-11ea-8775-c8d23647ecf3.png)

After adding this filter through the front end "Edit Form View", this is the results
![image](https://user-images.githubusercontent.com/39602586/90179308-1b227d00-dd62-11ea-9a51-fcfb2f00b007.png)

I believe this is the proper solution to this issue.

2020-08-14 14:20 UTC, marcelsavegnago approved these changes

2020-08-14 15:28 UTC, brian10048 approved these changes
Tested on runbot and functions as intended.

Thank you!

As a side note, should we update the filter names so we don't have 3 with the same name "order_upcoming_all"?

2020-08-24 20:12 UTC, brian10048 commented
@dreispt @osi-scampbell Can you review/merge https://github.com/ursais/field-service/pull/34 and then I'm good with merging this one to OCA

2020-08-24 20:37 UTC, bodedra approved these changes

2020-08-24 20:46 UTC, brian10048 commented
/ocabot merge patch

2020-08-24 20:57 UTC, merged