[12.0][FIX] Improved code of stage create method.
OCA/field-service pull request #643
Opened 2020-09-25 10:36 UTC by rutul-serpentcs

When I create stage from Field Service >> Dashboard >> Team >> Orders kanban view I got an error.

![Teams-Odoo](https://user-images.githubusercontent.com/71875607/94257170-84440580-ff48-11ea-8188-75564a8fc473.gif)

2020-09-25 15:37 UTC, brian10048 requested changes
@rutul-serpentcs 
This fixes the original error you presented.
However there is still an issue creating the stage from Kanban view

```
The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model: Field Service Stage (fsm.stage), Field: Type (stage_type) 
```
stage_type field needs to be set

2020-09-28 07:36 UTC, rutul-serpentcs commented
> @rutul-serpentcs
> This fixes the original error you presented.
> However there is still an issue creating the stage from Kanban view
> 
> ```
> The operation cannot be completed:
> - Create/update: a mandatory field is not set.
> - Delete: another model requires the record being deleted. If possible, archive it instead.
> 
> Model: Field Service Stage (fsm.stage), Field: Type (stage_type) 
> ```
> 
> stage_type field needs to be set

@brian10048 Done, Can you please review it again?

2020-09-28 16:28 UTC, brian10048 commented
@rutul-serpentcs - It allows to create the stage, but a new bug is introduced when we create a stage that has an undefined stage type.  When you go back to the orders kanban view, the stage recently created will not be displayed.

Can you revert the recent change and keep the stage_type required in python?  Then, instead can you use the context to set the correct `stage_type` based on the view

2020-10-07 08:31 UTC, dreispt commented on fieldservice/models/fsm_stage.py
> +                                   ('worker', 'Worker')], 'Type', require=True)
I'm afraid this is incorrect,  `required` is the correct field attribute.
Is the goal to remove the required attribute?

2020-10-07 08:31 UTC, dreispt commented on fieldservice/views/fsm_team.xml
> +            'default_stage_type':'order'}</field>
```suggestion
            'default_stage_type': 'order'}</field>
```

2020-10-07 08:31 UTC, dreispt commented on fieldservice/models/fsm_stage.py
> +               stage.sequence == vals.get('sequence'):
:+1:

2022-10-20 20:13 UTC, max3903 requested changes
Please attend the comments

2024-12-02 17:54 UTC, ivantodorovich commented
I think we can close this one (or remove the "no stale" label), given it's old and the comments haven't been taken care of.

2024-12-02 22:40 UTC, closed without merging