[12.0][IMP] fieldservice_maintenance: Convert Maintenance Equipment To FSM
OCA/field-service pull request #669
Opened 2020-11-11 02:23 UTC by osi-scampbell

The following PR adds a wizard that allows users to convert a Maintenance Equipment into an FSM Equipment similar to how we convert Contacts into FSM Records

2020-11-11 19:57 UTC, bodedra requested changes
Few points to improves:

- wizard should be `TransientModel`
- remove security file.
- create a lot number if product has tracking = serial or lot.

2020-11-11 19:57 UTC, bodedra commented on fieldservice_maintenance/wizard/maintenance_equipment_wizard.py
> +class MainenanceEquipmentWizard(models.Model):
```suggestion
class MainenanceEquipmentWizard(models.TransientModel):
```

2020-11-11 19:57 UTC, bodedra commented on fieldservice_maintenance/__manifest__.py
> +        'security/ir.model.access.csv',
```suggestion
```

2020-11-11 19:58 UTC, bodedra commented on fieldservice_maintenance/wizard/maintenance_equipment_wizard.py
> +            if not maintenance_id.serial_no or not maintenance_id.serial_no:
`maintenance_id.serial_no` condition appear twice in a condition.

2020-11-17 04:09 UTC, bodedra requested changes
@osi-scampbell 

add this changes and squash your commits.

Once this is green, I will review it.

2020-11-17 04:09 UTC, bodedra commented on fieldservice_maintenance/models/maintenance_equipment.py
> +from odoo import api, fields, models
```suggestion
from odoo import fields, models
```

2020-11-18 21:45 UTC, bodedra requested changes
Functional review :+1:

2020-11-18 21:46 UTC, bodedra commented
@brian10048 @hparfr @marcelsavegnago Are you guys available to review this?

2020-11-19 02:39 UTC, bodedra approved these changes

2020-11-19 10:32 UTC, hparfr approved these changes
I'm not familiar with fsm_equipements so I don't know what are the benefits of the "convert to..."

If you want to align with fsm_location you will have to "inherits" https://github.com/OCA/field-service/blob/12.0/fieldservice/models/fsm_location.py#L10

Are you sure adding product_id should be part of this PR ?

2020-11-19 10:32 UTC, hparfr commented on fieldservice_maintenance/wizard/maintenance_equipment_wizard.xml
> +            <form string="Convert to a Field Service Worker or Location">
wrong string

2020-11-19 14:23 UTC, marcelsavegnago approved these changes

2020-11-20 18:28 UTC, osi-scampbell commented
> I'm not familiar with fsm_equipements so I don't know what are the benefits of the "convert to..."
> 
> If you want to align with fsm_location you will have to "inherits" https://github.com/OCA/field-service/blob/12.0/fieldservice/models/fsm_location.py#L10
> 
> Are you sure adding product_id should be part of this PR ?

When an FSM Equipment is created, a Maintenance Equipment is automatically created. However when you create a Maintenance Equipment, an FSM Equipment is not automatically created. So this lets users take a maintenance equipment that has already been created and convert it to an FSM Equipment. 

You bring up a very good point about the product_id addition, I have had others ask the same question. I added this because on an FSM Equipment, product_id and lot_id are required fields. Perhaps this shouldn't be the case considering they aren't needed on Maintenance Equipment so maybe they shouldn't be needed on FSM Equipment? I will follow up on this question today and get back to you, I am not sure what the ramifications would be if we made product_id and lot_id no longer required on FSM Equipment

2020-11-22 14:03 UTC, dreispt commented
/ocabot merge minor

2020-11-28 16:49 UTC, dreispt commented
/ocabot merge minor

2020-12-07 08:23 UTC, dreispt commented
https://travis-ci.com/github/OCA/field-service/jobs/450063553#L602

2020-12-07 16:00 UTC, osi-scampbell commented
@dreispt It looks like these are lint errors in JavaScript that are in fieldservie and in fieldservice_vehicle_stock. Should those be fixed in this PR or should they be in a separate PR since they are in separate modules?

2022-07-04 13:47 UTC, marcelsavegnago commented
ping @dreispt

2022-07-05 18:23 UTC, dreispt commented
/ocabot merge minor

2022-10-20 20:14 UTC, max3903 commented
/ocabot merge minor

2022-10-20 20:30 UTC, merged