[14.0][IMP] fieldservice: add fsm_location as res.partner type
OCA/field-service pull request #748
Opened 2021-03-23 09:33 UTC by hparfr

replace #696

2021-03-26 18:31 UTC, hparfr commented
ping @mourad-ehm

2021-04-09 08:40 UTC, mourad-ehm approved these changes

2021-05-07 22:22 UTC, patrickrwilson requested changes
Just one small item, LGTM after change.

2021-05-07 22:22 UTC, patrickrwilson commented on fieldservice/models/res_partner.py
> +    type = fields.Selection(selection_add=[("fsm_location", "Location")])
14.0 Requires ondelete= attribute. See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

2021-06-30 15:35 UTC, mourad-ehm approved these changes

2021-12-04 19:21 UTC, dreispt commented
/ocabot merge minor

2021-12-14 12:46 UTC, chienandalu commented
The merge command didn't have effect

2021-12-14 13:55 UTC, dreispt commented
/ocabot merge minor

2021-12-14 14:29 UTC, merged