[MIG][14.0]Migrated a fieldservice_timeline module.
OCA/field-service pull request #758
Opened 2021-04-09 09:05 UTC by AmmarOfficewalaSerpentCS

2021-04-09 09:27 UTC, AmmarOfficewalaSerpentCS commented
@smangukiya , @murtuzasaleh , @dreispt , @max3903 ,
Can you please review this PR?

2021-04-09 15:33 UTC, smangukiya commented on fieldservice_timeline/__init__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
@AmmarOfficewalaSerpentCS Correct the copyrights in all files, please?

# Copyright (C) 2021 Open Source Integrators
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

2021-04-09 15:35 UTC, smangukiya requested changes
There is orr_disable_autofill/__init__.py file in this PR. Please remove it.

2021-04-21 23:18 UTC, smangukiya approved these changes
Looks good to me.

2021-04-22 08:55 UTC, dreispt commented
/ocabot merge nobump

2021-04-22 09:30 UTC, merged