[14.0][MIG] fieldservice_sale_recurring
OCA/field-service pull request #765
Opened 2021-04-16 14:20 UTC by Freni-OSI

2021-12-03 18:50 UTC, brian10048 requested changes

2021-12-03 18:50 UTC, brian10048 commented on fieldservice_sale_recurring/models/sale_order_line.py
> +            "customer_id": self.order_id.partner_id.id,
```suggestion
```
there is no customer_id on fsm.recurring

2021-12-03 18:50 UTC, brian10048 commented on fieldservice_sale_recurring/models/sale_order_line.py
> +            "sale_id": self.order_id.id,
```suggestion
```
There is no sale_id on fsm.recurring

2022-10-03 16:31 UTC, max3903 commented
@Freni-OSI Please fix or close.

2022-10-04 07:18 UTC, Freni-OSI commented
Closing as merged another PR in v14.

2022-10-04 07:18 UTC, closed without merging