[14.0][BUG] fixed object has no attribute 'group_manage_vendor_price' error
OCA/field-service pull request #766
Opened 2021-04-16 23:28 UTC by ReedHayashikawa

2021-04-22 16:07 UTC, brian10048 requested changes
Thank you for these bug fixes @ReedHayashikawa 

I have made some suggestions to this

2021-04-22 16:07 UTC, brian10048 commented on fieldservice/__manifest__.py
> +    "depends": ["base_territory", "base_geolocalize", "resource", "contacts", "mail"],
I don't believe we need to explicitly add the `mail` dependency.  It is already implied through the `contacts` dependency

2021-04-22 16:07 UTC, brian10048 commented on fieldservice/models/res_config_settings.py
>          if self.module_fieldservice_purchase:
```suggestion

```
We should be able to remove this completely since the group has been completely removed from Odoo

2021-04-22 16:07 UTC, brian10048 commented on fieldservice/models/fsm_person.py
> +    _inherit = "mail.thread.cc"
```suggestion
    _inherit = "mail.thread"
```

2022-03-02 18:05 UTC, smangukiya approved these changes

2022-03-02 18:05 UTC, smangukiya commented
/ocabot merge minor

2022-03-02 18:14 UTC, merged