[imp] fieldservice stock
OCA/field-service pull request #81
Opened 2018-12-31 10:57 UTC by smangukiya

ref: https://github.com/OCA/field-service/issues/65

@max3903 : Please review it. Thanks

2019-01-02 15:53 UTC, max3903 requested changes

2019-01-02 15:53 UTC, max3903 commented on fieldservice_stock/models/fsm_equipment.py
> +                    equipment.lot_id.product_id.property_stock_inventory \
@smangukiya `current_location_location_id` should be set to the current location of the serial number: when the serial number is delivered to the customer location, the current location should change to `Partner Location / Customers`.

2019-01-02 15:53 UTC, max3903 commented on fieldservice_stock/models/fsm_order.py
> +                self.return_ids._confirm_picking()
@smangukiya It doesn't work if I have a return line (inbound) and no line (outbound). I keep getting the error message below. Confirming should confirm the draft lines and draft returns if there is any.

2019-01-02 15:57 UTC, max3903 commented on fieldservice_stock/models/fsm_order.py
> +                self.return_ids._confirm_picking()
@smangukiya I fixed the logic but we still need to filter the lines and returns with draft ones.

2019-01-02 22:49 UTC, max3903 commented on fieldservice_stock/models/fsm_equipment.py
> +        'stock.production.lot', string='Lot/Serial #')
@smangukiya We also need a `product_id` field to filter the lot_id. Both fields should be required.

2019-01-03 10:41 UTC, smangukiya commented
@max3903 : Source has been improved as per your comments:
1. No need for "Lot/". We need a product_id field to filter the lot_id. Both fields should be required
2. I fixed the logic but we still need to filter the lines and returns with draft ones.
3. current_location_location_id should be set to the current location of the serial number: when the serial number is delivered to the customer location, the current location should change to Partner Location / Customers.

2019-01-03 16:37 UTC, max3903 approved these changes

2019-01-03 17:05 UTC, merged