[WIP][15.0][MIG] fieldservice
OCA/field-service pull request #881
Opened 2022-01-07 13:20 UTC by Chanakya-OSI

2022-01-07 14:29 UTC, brian10048 commented
/ocabot migration

2022-01-07 14:32 UTC, brian10048 commented
/ocabot migration fieldservice

2022-02-10 09:20 UTC, Murtaza-OSI commented on fieldservice/models/fsm_category.py
> +                record.full_name = record.parent_id.name + "/" + record.name
Used full_name instead of name @AmmarOfficewalaSerpentCS @Freni-OSI

2022-02-10 09:22 UTC, Murtaza-OSI commented on fieldservice/models/fsm_equipment.py
> +    hide = fields.Boolean(default=False)
It necessary Set Default False ?

2022-02-10 09:25 UTC, Murtaza-OSI commented on fieldservice/models/fsm_equipment.py
> +        return stage_ids
Remove assign variable and return directly @Freni-OSI

2022-02-10 09:28 UTC, Murtaza-OSI commented on fieldservice/models/fsm_equipment.py
> +            order="sequence asc",
Used Limit 1

2022-02-10 09:29 UTC, Murtaza-OSI commented on fieldservice/models/fsm_equipment.py
> +            self.stage_id = next_stage[0]
Improved the code

2022-02-10 09:30 UTC, Murtaza-OSI commented on fieldservice/models/fsm_equipment.py
> +            order="sequence desc",
Used limit 1

2022-02-10 09:31 UTC, Murtaza-OSI commented on fieldservice/models/fsm_equipment.py
> +            self.hide = False
Convert to single line code

2022-02-10 09:31 UTC, Murtaza-OSI commented on fieldservice/models/fsm_location.py
> +    direction = fields.Char()
Add String

2022-02-10 09:35 UTC, Murtaza-OSI commented on fieldservice/models/fsm_location.py
> +    hide = fields.Boolean(default=False)
It is necessary set default False?

2022-02-10 09:41 UTC, Murtaza-OSI commented on fieldservice/models/fsm_location.py
> +            order="sequence asc",
Add limit 1

2022-02-10 09:41 UTC, Murtaza-OSI commented on fieldservice/models/fsm_location.py
> +            order="sequence desc",
Add limit 1

2022-02-10 09:42 UTC, Murtaza-OSI commented on fieldservice/models/fsm_location.py
> +            self.hide = False
Convert single line code

2022-02-10 09:44 UTC, Murtaza-OSI commented on fieldservice/models/fsm_location.py
> +            loc.equipment_count = equipment
Convert single Line

2022-02-10 09:45 UTC, Murtaza-OSI commented on fieldservice/models/fsm_location.py
> +            loc.sublocation_count = sublocation
Convert single line

2022-02-10 10:05 UTC, Murtaza-OSI commented on fieldservice/models/fsm_order.py
> +            return stage_ids[0]
Not necessary used [0]

2022-02-10 10:05 UTC, Murtaza-OSI commented on fieldservice/models/fsm_order.py
> +            raise ValidationError(_("You must create an FSM order stage first."))
Remove else put raise out

2022-02-10 10:06 UTC, Murtaza-OSI commented on fieldservice/models/fsm_order.py
> +            raise ValidationError(_("You must create an FSM team first."))
Same As above

2022-02-10 10:08 UTC, Murtaza-OSI commented on fieldservice/models/fsm_order.py
> +        duration = 0.0
Declare duration inside for loop

2022-02-10 10:12 UTC, Murtaza-OSI requested changes
@Freni-OSI

2022-02-10 10:16 UTC, Murtaza-OSI commented on fieldservice/models/fsm_person.py
> +            self.hide = False
Convert single line

2022-02-10 10:21 UTC, Murtaza-OSI commented on fieldservice/models/fsm_stage.py
> +        stages = self.env["fsm.stage"].search([])
stages = self.search([])

2022-02-10 10:29 UTC, Murtaza-OSI commented on fieldservice/models/res_partner.py
> +            partner.owned_location_count = res
Assign value directly remove variable

2022-02-10 10:31 UTC, Murtaza-OSI commented on fieldservice/wizard/fsm_wizard.py
> +            self.env["fsm.location"].create(vals)
Remove vals and put self._prepare_fsm_location(partner) in create

2022-02-10 10:32 UTC, Murtaza-OSI commented on fieldservice/wizard/fsm_wizard.py
> +        if res == 0:
Convert to one line 
if not used search_count

2022-02-10 10:33 UTC, Murtaza-OSI commented on fieldservice/wizard/fsm_wizard.py
> +        if res == 0:
Convert to one line
if not used search_count

2022-02-10 10:34 UTC, Murtaza-OSI commented on fieldservice/wizard/fsm_wizard.py
> +            )
Remove else take out raise

2022-02-10 10:34 UTC, Murtaza-OSI commented on fieldservice/wizard/fsm_wizard.py
> +            )
Remove else take out raise

2022-02-10 10:35 UTC, Murtaza-OSI requested changes
@Freni-OSI

2022-04-04 22:41 UTC, smangukiya commented
@Murtaza-OSI @Freni-OSI Can you please turn all the checks to green?

2022-04-12 15:49 UTC, smangukiya commented
@Freni-OSI This looks better, can you consider the code coverage % too? Thanks

2022-04-13 14:57 UTC, Freni-OSI commented
> @Freni-OSI This looks better, can you consider the code coverage % too? Thanks

It's done now. you can proceed to merge it

2022-04-13 19:31 UTC, smangukiya commented
> > @Freni-OSI This looks better, can you consider the code coverage % too? Thanks
> 
> It's done now. you can proceed to merge it

Thank you @Freni-OSI for tests but code coverage % is still doesn't complete. Please click on 'Details' link which is right besides codecov/patch line for more details

![image](https://user-images.githubusercontent.com/13784881/163256017-4abcffb1-88d7-4ae0-a3c6-58678edd8285.png)

2022-06-04 19:06 UTC, brian10048 requested changes

2022-06-04 19:06 UTC, brian10048 commented on fieldservice/models/fsm_category.py
> +        required=True,
Will this require a migration script to set a company_id in case it is not set previously?

2022-06-04 19:06 UTC, brian10048 commented on fieldservice/models/fsm_person.py
> -    active = fields.Boolean(default=True)
Why is this feature being removed?

2022-06-04 19:06 UTC, brian10048 commented on fieldservice/security/res_groups.xml
> -    <record id="group_fsm_user_own" model="res.groups">
Why is this group being removed?

2022-06-04 19:06 UTC, brian10048 commented on fieldservice/tests/test_fsm_category.py
> +# Copyright (C) 2019 Brian McMaster <brian@mcmpest.com>
Please fix copyright

2022-06-04 19:06 UTC, brian10048 commented on fieldservice/tests/test_fsm_category.py
> +    def test_fsm_order_category(self):
Should the test check the name is correct?

2022-08-09 09:09 UTC, victoralmau commented
Superseed by: https://github.com/OCA/field-service/pull/950

2022-08-09 11:24 UTC, closed without merging

2022-08-09 11:26 UTC, pedrobaeza commented on fieldservice/models/fsm_category.py
> +        required=True,
No, it doesn't require it

2022-08-09 11:27 UTC, pedrobaeza commented on fieldservice/models/fsm_category.py
> +        required=True,
Sorry, I mean it shouldn't be required now. It's an incorrect change. cc @victoralmau

2022-08-09 11:37 UTC, victoralmau commented on fieldservice/models/fsm_category.py
> +        required=True,
Please can you comment on this change in the other PR? I don't understand the need to change this field to required in v15 (in v14 it is not required).

2022-08-09 11:38 UTC, pedrobaeza commented on fieldservice/models/fsm_category.py
> +        required=True,
That's why I want you to remove this change, as it should remain as not required.